whaledoc:
  version: ${project.version}

  api:
    url: ${whaledoc.api.url}

  releases:
    url: ${whaledoc.releases.url}

  endpoints:
    cliAuthSessions: /cli/auth/sessions
    cliWebhookEvents: /cli/webhooks/events