#!/bin/sh
# Prints the Homebrew formula for a release, for the whaledoc/homebrew-tap repository.
#
#   packaging/homebrew/formula.sh 1.2.0 checksums.txt > Formula/whaledoc.rb
#
# checksums.txt is the file published with each release (sha256sum format).

set -eu

VERSION="$1"
CHECKSUMS="$2"
REPO="whaledoc/whaledoc-cli"

checksum() {
    sha="$(grep " whaledoc-$1.tar.gz\$" "$CHECKSUMS" | cut -d ' ' -f 1)"

    if [ -z "$sha" ]; then
        echo "error: no checksum for whaledoc-$1.tar.gz in $CHECKSUMS" >&2
        exit 1
    fi

    echo "$sha"
}

MACOS_ARM64="$(checksum macos-arm64)"
MACOS_X64="$(checksum macos-x64)"
LINUX_ARM64="$(checksum linux-arm64)"
LINUX_X64="$(checksum linux-x64)"
DOWNLOAD="https://github.com/$REPO/releases/download/v$VERSION"

cat <<EOF
# Generated by the release workflow of https://github.com/$REPO. Don't edit it by hand:
# changes are overwritten by the next release.
class Whaledoc < Formula
  desc "Official command-line interface for WhaleDoc"
  homepage "https://whaledoc.io"
  version "$VERSION"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$DOWNLOAD/whaledoc-macos-arm64.tar.gz"
      sha256 "$MACOS_ARM64"
    end

    on_intel do
      url "$DOWNLOAD/whaledoc-macos-x64.tar.gz"
      sha256 "$MACOS_X64"
    end
  end

  on_linux do
    on_arm do
      url "$DOWNLOAD/whaledoc-linux-arm64.tar.gz"
      sha256 "$LINUX_ARM64"
    end

    on_intel do
      url "$DOWNLOAD/whaledoc-linux-x64.tar.gz"
      sha256 "$LINUX_X64"
    end
  end

  def install
    bin.install "whaledoc"
  end

  test do
    assert_match "WhaleDoc version #{version}", shell_output("#{bin}/whaledoc --version")
  end
end
EOF
